- name: SYSOP
  ip: '000.000.000.000'
  password: STUPID
  citystate: 'Tempe, AZ'
  address: '600 E. Solana Drive'
  length: 24
  width: 80
  ansi: true
  more: true
  level: 255
  fullscreen: false
  
- name: DOVEQWK 
  ip: '000.000.000.000'
  password: '123456'
  citystate: 'NO STREET'
  address: 'NO ADDRESS'
  length: 24
  width: 80
  ansi: false
  more: true
  level: 255
  fullscreen: false

- name: PARAQWK 
  ip: '000.000.000.000'
  password: '123456'
  citystate: 'NO STREET'
  address: 'NO ADDRESS'
  length: 24
  width: 80
  ansi: false
  more: true
  level: 255
  fullscreen: false
  
- name: FIDONET
  ip: '000.000.000.000'
  password: '123456'
  citystate: 'NO STREET'
  address: 'NO ADDRESS'
  length: 24
  width: 80
  ansi: false
  more: true
  level: 255
  fullscreen: false
