- name: SYSOP
  ip: '000.000.000.000'
  password: STUPID
  citystate: 'Tempe, AZ'
  address: '123 Sample Street'
  length: 24
  width: 80
  ansi: true
  more: true
  level: 255
  fullscreen: false
  sex: 'M'
  alias: 'SYSOP'
  
- name: SYSTEM
  ip: '000.000.000.000'
  password: STUPID
  citystate: 'Tempe, AZ'
  address: '123 Sample Street'
  length: 24
  width: 80
  ansi: true
  more: true
  level: 0
  fullscreen: false
  sex: 'M'
  alias: 'SYSTEM'
  
- name: DOVEQWK 
  ip: '000.000.000.000'
  password: '123456'
  citystate: 'NO STREET'
  address: 'NO ADDRESS'
  length: 24
  width: 80
  ansi: false
  more: true
  level: 0
  fullscreen: false
  sex: 'M'
  alias: 'DOVEQWK'
  
- name: PARAQWK 
  ip: '000.000.000.000'
  password: '123456'
  citystate: 'NO STREET'
  address: 'NO ADDRESS'
  length: 24
  width: 80
  ansi: false
  more: true
  level: 0
  fullscreen: false
  sex: 'M'
  alias: 'PARAQWK'
  
- name: FIDONET
  ip: '000.000.000.000'
  password: '123456'
  citystate: 'NO STREET'
  address: 'NO ADDRESS'
  length: 24
  width: 80
  ansi: false
  more: true
  level: 0
  fullscreen: false
  sex: 'M'
  alias: 'FIDONET'
  
- name: GIGANEWS
  ip: '000.000.000.000'
  password: '123456'
  citystate: 'NO STREET'
  address: 'NO ADDRESS'
  length: 24
  width: 80
  ansi: false
  more: true
  level: 0
  fullscreen: false
  sex: 'M'
  alias: 'GIGANEWS'
  
- name: BBSINFO
  ip: '000.000.000.000'
  password: '123456'
  citystate: 'NO STREET'
  address: 'NO ADDRESS'
  length: 24
  width: 80
  ansi: false
  more: true
  level: 0
  fullscreen: false
  sex: 'M'
  alias: 'BBSINFO'
