- cmd: areachange
  theme_key: 2
  ulevel: 0
  menu_item: A
  
- cmd: masskill
  theme_key: 1
  ulevel: 255
  menu_item: MK
  
- cmd: smaint
  theme_key: 1
  ulevel: 255
  menu_item: SM
  
- cmd: gmaint
  theme_key: 2
  ulevel: 0
  menu_item: GM

- cmd: leave
  theme_key: 2
  ulevel: 0
  menu_item: G

- cmd: umaint
  theme_key: 2
  ulevel: 255
  menu_item: UM

- cmd: kill_log
  theme_key: 2
  ulevel: 255
  menu_item: KL

- cmd: amaint
  theme_key: 2
  ulevel: 255
  menu_item: AM

- cmd: log
  theme_key: 2
  ulevel: 0
  menu_item: U
  
- cmd: sysopmnu
  theme_key: 2
  ulevel: 255
  menu_item: X
  
- cmd: bmaint
  theme_key: 2
  ulevel: 255
  menu_item: BM

- cmd: bulletins
  theme_key: 2
  ulevel: 0
  menu_item: B
  
- cmd: teleconference
  theme_key: 2
  ulevel: 0
  menu_item: T

- cmd: kick
  theme_key: 2
  ulevel: 255
  menu_item: KU

- cmd: questionaire
  theme_key: 2
  ulevel: 0
  menu_item: Q

- cmd: email
  theme_key: 2
  ulevel: 0
  menu_item: V

- cmd: dmaint
  theme_key: 2
  ulevel: 255
  menu_item: DM

- cmd: tmaint
  theme_key: 2
  ulevel: 255
  menu_item: TM

- cmd: omaint
  theme_key: 2
  ulevel: 255
  menu_item: OM

- cmd: doors
  theme_key: 2
  ulevel: 0
  menu_item: D

- cmd: other
  theme_key: 2
  ulevel: 0
  menu_item: O

- cmd: feedback
  theme_key: 2
  ulevel: 0
  menu_item: F

- cmd: post
  theme_key: 2
  ulevel: 0 
  menu_item: E

- cmd: usrsetting
  theme_key: 2
  ulevel: 0
  menu_item: C

- cmd: readmnu
  theme_key: 2
  ulevel: 0
  menu_item: R

- cmd: zipread
  theme_key: 2
  ulevel: 0
  menu_item: Z

- cmd: page
  theme_key: 2
  ulevel: 0
  menu_item: PU

- cmd: info
  theme_key: 2
  ulevel: 0
  menu_item: S
  
- cmd: version
  theme_key: 2
  ulevel: 0
  menu_item: CR

- cmd: who
  theme_key: 2
  ulevel: 0
  menu_item: W

- cmd: sysopmenu
  theme_key: 2
  ulevel: 255
  menu_item: X

- cmd: mainmnu
  theme_key: 2
  ulevel: 0
  menu_item: '?'

- cmd: reread
  theme_key: 2
  ulevel: 0
  menu_item: '/'
  
- cmd: killmsg
  theme_key: 2
  ulevel: 0
  menu_item: K
  
- cmd: replymsg
  theme_key: 2
  ulevel: 0
  menu_item: R
  
- cmd: fullheader
  theme_key: 2
  ulevel: 0
  menu_item: FH

- cmd: sysopmenu
  theme_key: 2
  ulevel: 255
  menu_item: X

- cmd: readmenu
  theme_key: 2
  ulevel: 0
  menu_item: '?'

- cmd: readquit
  theme_key: 2
  ulevel: 0
  menu_item: Q
    
- cmd: bullquit
  theme_key: 2
  ulevel: 0
  menu_item: Q

- cmd: bullmenu
  theme_key: 2
  ulevel: 0
  menu_item: '?'
  
- cmd: doormenu
  theme_key: 2
  ulevel: 0
  menu_item: '?'

- cmd: doorquit
  theme_key: 2
  ulevel: 0
  menu_item: Q

- cmd: screenmenu
  theme_key: 2
  ulevel: 0
  menu_item: '?'

- cmd: screenquit
  theme_key: 2
  ulevel: 0
  menu_item: Q

- cmd: bbslist
  theme_key: 2
  ulevel: 0
  menu_item: O

- cmd: bbsquit
  theme_key: 2
  ulevel: 0
  menu_item: Q

- cmd: bbsadd
  theme_key: 2
  ulevel: 0
  menu_item: A
  
- cmd: bbslock
  theme_key: 2
  ulevel: 0
  menu_item: L
  
- cmd: bbsdelete
  theme_key: 2
  ulevel: 0
  menu_item: K
  
- cmd: bbsreload
  theme_key: 2
  ulevel: 0
  menu_item: '/'
  
- cmd: bbscont
  theme_key: 2
  ulevel: 0
  menu_item: 'C'
  
- cmd: uprofile
  theme_key: 2
  ulevel: 0
  menu_item: 'U'

- cmd: upalpha
  theme_key: 2
  ulevel: 0
  menu_item: 'D'
  
- cmd: upadd
  theme_key: 2
  ulevel: 0
  menu_item: 'Y'
  
- cmd: upbrowse
  theme_key: 2
  ulevel: 0
  menu_item: 'B'
  
- cmd: upfind
  theme_key: 2
  ulevel: 0
  menu_item: 'L'
  
- cmd: upinfo
  theme_key: 2
  ulevel: 0
  menu_item: 'I'

- cmd: upexit
  theme_key: 2
  ulevel: 0
  menu_item: 'Q'
  
- cmd: upmenu
  theme_key: 2
  ulevel: 0
  menu_item: '?'