VERT                                                                                                                             2001   07-12-1023:57JON JUSTVIG              MARK FIRESTONE           test                                         3          *γγA test from the new version of QBBS.  I rewrote the qwk connector.  I γhope it does't screw up...γγγ---γώ retroCOMPUTING BBS - Home of QUARKware ώ telnet 81.96.235.250 2323γ                                                                                 