VERT                                                                                                                             2001   03-05-1523:57MRO                      the doctor               Re: CLI vs GUI                               3          *„>„>„> if that was around that time period, that's dirt chea„„I remember spending $300 on a 300 baud internal Apple 2 modem...„„„„---„* TARDIS BBS - Home of QUARKware * telnet bbs.cortex-media.info„                                                          